# Auto-generated by mcc. Do not modify.
	.file "input.c"
	.text
	.align	3
mcc_format:
	.string	"%d\n"
	.align	1
	.globl main
	.type main, @function
main:
	addi	sp, sp, -24
	sd	ra, 0(sp)
	sd	s0, 8(sp)
	addi	s0, sp, 24
	li	a1, 5
	lla	a3, a
	sw	a1, 0(a3)
	lla	a3, a
	lw	a1, 0(a3)
	sw	a1, 16(sp)
	li	a1, 2
	sw	a1, 20(sp)
	li	a1, 5
	lw	a2, 20(sp)
	mulw	a1, a1, a2
	lw	a2, 16(sp)
	addw	a1, a1, a2
	lla	a3, b
	sw	a1, 0(a3)
	lla	a3, b
	lw	a1, 0(a3)
	lla	a0, mcc_format
	call printf
	li	a5, 0
	mv	a0, a5
	ld	ra, 0(sp)
	ld	s0, 8(sp)
	addi	sp, sp, 24
	jr	ra

	.section	.sdata
	.global	a
	.align	2
	.type	a, @object
	.size	a, 4
a:
	.zero	4
	.global	b
	.align	2
	.type	b, @object
	.size	b, 4
b:
	.zero	4
# End and bye.

